##
## surf
## Simple commands to control with dune
##

.PHONY: default run build test install uninstall clean fmt

default: run

run:
	dune exec surf

build:
	dune build

test:
	dune runtest -f

install:
	dune install

uninstall:
	dune uninstall

clean:
	dune clean

fmt:
	dune fmt 

