##
## surf
## dune/opam project
##

.PHONY: default run build test install uninstall clean fmt

default: run

run:
	dune exec surf

build:
	dune build

test:
	dune runtest -f

clean:
	dune clean

fmt:
	dune fmt 

