name: Builds

on:
  push:
    branches:
      - main
      - dev
      - feat/project-setup
  pull_request:
    paths-ignore:
      - 'build/**'
      - '.vs/**'
      - '.vscode/**'
      - '**/*.md'
      - '*.git*'

jobs:
  win32-debug:
    name: Win32 Debug
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.x'

      - name: Build project
        run: python ./surf.py

      - name: Run msbuild
        run: msbuild ./build/surf.sln -interactive:False -property:Configuration=Debug -m

  win32-release:
    name: Win32 Release
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.x'

      - name: Build project
        run: python3 ./surf.py

      - name: Run msbuild
        run: msbuild ./build/surf.sln -interactive:False -property:Configuration=Release -m